name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint adnuntius python-dateutil
    - name: Analysing the code with pylint
      run: |
        pylint --disable too-few-public-methods,too-many-arguments,too-many-locals,unused-argument,too-many-instance-attributes adnbidder/bidder.py
